### ISSUE TITLE
OSError: orientpy/dispmaps/R.gv.10.txt not found.

### ISSUE THREAD

**Issue by Chu-Te-Ethan-Chen** [nfsi-canada/OrientPy#12]
Hi,
I ran into an error when trying to run dl_calc.py
```
$ dl_calc.py --min-mag=6. YH_list.pkl
   Establishing Catalogue Client...
      Done
   Establishing Waveform Client...
      Done
 
|==============================================|
|                      LOBS3                   |
|==============================================|
|  Station: YH.LOBS3                           |
|      Channel: HH; Locations: --              |
|      Lon:  179.15; Lat: -38.79               |
|      Start time: 2014-05-15 00:00:00         |
|      End time:   2015-06-23 23:59:59         |
| Output Directory:  DL_RESULTS
| Save Progress:  True
|----------------------------------------------|
| Searching Possible events:                   |
|   Start: 2014-05-15 00:00:00                 |
|   End:   2015-06-23 23:59:59                 |
|   Mag:   >{0:3.1f} 6.0                       |
|   Min Distance:  5.0
|   Max Distance:  175.0
|   Max Depth:     150.0
|   Request Event Catalogue...                 |
| ...                                          |
|   Retrieved 178 events 

 
**************************************************
* (3/178):  20150620_021007 YH.LOBS3
*   Origin Time: 2015-06-20 02:10:07
*   Lat: -36.33;        Lon:  -73.67
*   Dep:  17.40 km;     Mag: 6.4
*   Dist: 8837.94 km;   Epi dist:  79.48 deg
*   Baz:  128.47 deg;   Az: 229.25 deg
* Requesting Waveforms: 
*    Startime: 2015-06-20 02:10:07
*    Endtime:  2015-06-20 06:10:07
*     LOBS3.HH - ZNE:
*          HH[ZNE].-- - Checking Network
*          HH[Z12].-- - Checking Network
*              - Z12 Data Downloaded
* Start times are not all close to true start: 
*   HH1 2015-06-20T02:10:07.650900Z 2015-06-20T06:10:07.638703Z
*   HH2 2015-06-20T02:10:07.651100Z 2015-06-20T06:10:07.638903Z
*   HHZ 2015-06-20T02:10:07.659300Z 2015-06-20T06:10:07.637103Z
*   True start: 2015-06-20T02:10:07.650000Z
* -> Shifting traces to true start
* Sampling rate is not an integer value:  100.00001525878906
* -> Resampling
* Waveforms Retrieved...
Traceback (most recent call last):
  File "/home/chen/.conda/envs/orient/bin/dl_calc.py", line 223, in <module>
    main()
  File "/home/chen/.conda/envs/orient/bin/dl_calc.py", line 208, in main
    dldata.calc(showplot=False)
  File "/home/chen/.conda/envs/orient/lib/python3.7/site-packages/orientpy/classes.py", line 548, in calc
    'dispmaps/R.gv.10.txt'))
  File "/home/chen/.conda/envs/orient/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1065, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/chen/.conda/envs/orient/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 194, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/chen/.conda/envs/orient/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 531, in open
    raise IOError("%s not found." % path)
OSError: /home/chen/.conda/envs/orient/lib/python3.7/site-packages/orientpy/dispmaps/R.gv.10.txt not found.
```

evironment:
Fedora 31(5.8.6-101.fc31.x86_64), python=3.7

reproduction:
1. Install OrientPy
I download the Orientpy.zip from [OrientPy: Seismic station orientation tools ](https://zenodo.org/record/3905404#.YFAg1nUzYUG)
```
conda create -n orient python=3.7 obspy -c conda-forge
conda activate orient
pip install stdb
pip install geographiclib
```
2. Install Stdb and create YH_list
I ran into some errors when trying to execute query_fdsn_stdb.py.
[Can't import Stdb due to lack of PyQt files](https://github.com/schaefferaj/StDb/issues/19)
```
git clone https://github.com/schaefferaj/StDb.git
cd StDb
pip install .
cd Scripts
pip uninstall pyqt5
conda install -c anacona pyqt
query_fdsn_stdb.py -N YH -C '?H?' -S LOBS3 YH_list > logfile
```
3. DL analysis
```
dl_calc.py --min-mag=6. YH_list.pkl
```

**Comment by Chu-Te-Ethan-Chen** [comment]
I fixed this problem when reinstalling the OrientPy from the `git clone https://github.com/nfsi-canada/OrientPy.git`.
