### ISSUE TITLE
GEOFON /GFZ data retrieving error - Orientpy/StDb

### ISSUE THREAD

**Issue by DasunSenana** [nfsi-canada/OrientPy#22]
@paudetseis 

During the **GFZ - GE network data retrieving**, There were several issues occurred as follows;

Traceback (most recent call last):
  File "/home/vboxuser/anaconda3/lib/python3.11/http/client.py", line 592, in _read_chunked
    value.append(self._safe_read(chunk_left))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/anaconda3/lib/python3.11/http/client.py", line 633, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(21 bytes read, 13 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vboxuser/anaconda3/lib/python3.11/site-packages/obspy/clients/fdsn/client.py", line 1958, in download_url
    reader = url_obj.read()
             ^^^^^^^^^^^^^^
  File "/home/vboxuser/anaconda3/lib/python3.11/http/client.py", line 460, in read
    return self._read_chunked(amt)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/anaconda3/lib/python3.11/http/client.py", line 598, in _read_chunked
    raise IncompleteRead(b''.join(value)) from exc
http.client.IncompleteRead: IncompleteRead(188488 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vboxuser/anaconda3/lib/python3.11/site-packages/orientpy/scripts/bng_calc_auto.py", line 437, in main
    cat = cat_client.get_events(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/anaconda3/lib/python3.11/site-packages/obspy/clients/fdsn/client.py", line 550, in get_events
    data_stream = self._download(url)
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/anaconda3/lib/python3.11/site-packages/obspy/clients/fdsn/client.py", line 1482, in _download
    code, data = download_url(
                 ^^^^^^^^^^^^^
  File "/home/vboxuser/anaconda3/lib/python3.11/site-packages/obspy/clients/fdsn/client.py", line 1962, in download_url
    raise HTTPException(msg)
http.client.HTTPException: Problem retrieving data from datacenter. Try reducing size of request.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vboxuser/anaconda3/bin/bng_calc_auto", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/vboxuser/anaconda3/lib/python3.11/site-packages/orientpy/scripts/bng_calc_auto.py", line 441, in main
    raise(Exception("  Fatal Error: Cannot download Catalogue"))
Exception:   Fatal Error: Cannot download Catalogue

I want to request your feedback and helping hands regarding this issue. Thank you.

**Comment by paudetseis** [comment]
Hi @DasunSenana, Thank you for using OrientPy and for your inquiry. This seems to be a problem with the FDSN client, and not with OrientPy (see line: "Problem retrieving data from datacenter. Try reducing size of request."). I would suggest doing exactly that: making several calls to, e.g., `big_calc_auto` with smaller time ranges.
